changelog:
  exclude:
    labels:
      - tagpr
  categories:
    - title: Breaking Changes
      labels:
        - major
        - breaking-change
    - title: Features
      labels:
        - minor
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"

